name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-15  # Latest macOS with Xcode 16
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.app
    
    - name: Check Swift version
      run: swift --version
    
    - name: Build
      run: swift build
    
    - name: Test
      run: swift test
